### ISSUE TITLE
Document version of libui needed, include script to wrap headers

### ISSUE THREAD

**Issue by jgoldfar** [joa-quim/Libui.jl#2]
I would be interested in contributing to this project, but without an explicit library version, and/or the script used to wrap the library headers, it will require a lot of extra work. Is it possible for these things to be added to the repository?

**Comment by joa-quim** [comment]
Hi, thanks for the interest. As you saw, for a long time I don't update the repo but that is a consequence of the Libui development itself. I've been waiting that image draw capability is added to Libui and that, apparently, will be added when the Table branch will be merged in master. Than I intend to update it, but meanwhile I will have to restore my Clang.jl package because it was with it that I made this wrapper. And it doesn't help much that I work almost only on Windows. If you want to do it (use Clang to update), please by feel free.

**Comment by jgoldfar** [comment]
Ok; no problem. I do have experience using Clang.jl to generate Julia wrappers for libraries, so if you end up having any difficulty I would be happy to help. Thanks for putting the work into this package!

**Comment by joa-quim** [comment]
Thanks, I might do it.

**Comment by joa-quim** [comment]
Hi @jgoldfar, could you try to generate the wrapper for the alpha4? I tried to update my OSX version of Clang.jl but the thing is apparently broken. Fixed a first issue with JULIA_HOME but than it crashed Julia while trying to build Clang.jl

**Comment by jgoldfar** [comment]
Closed by PR #9
